# Python package
trigger:
- main

pool:
  vmImage: ubuntu-latest
strategy:
  matrix:
    Python3:
      python.version: '3.11'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'
      
- script: 
    python -m pip install --upgrade pip
    pip install selenium
    pip install pytest

- script:
#    pip install -r requirements.txt
  displayName: 'Install dependencies'
  
- script:
   #python tests --doctest-modules --junitxml=junit/test-results.xml
  # pytest -v -s TestLogin.py
  # python -m pytest tests --junitxml=junit/test-results.xml
   pytest -s -v  --html=Reports\report.html testCases/test_login.py

  displayName: 'Execute tests'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/TEST-*.xml'

